apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ijp
  region: us-east-1

managedNodeGroups:
  - name: ijp
    instanceType: m5.large
    desiredCapacity: 3      # 3 instance we are taken 
    spot: true
    # availabilityZones:
    # - us-east-1f